FROM ubuntu:latest

RUN apt-get update && apt-get install -y cron curl && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /entrypoint.sh
COPY cron_runner.sh /cron_runner.sh
RUN chmod +x /entrypoint.sh
RUN chmod +x /cron_runner.sh

RUN touch /var/log/cron.log

ENTRYPOINT ["/entrypoint.sh"]
