FROM ubuntu:latest

# Instalar cron
RUN apt-get update && apt-get install -y cron curl

# Adicionar seus scripts de cron
# Adicionar apenas o entrypoint script, as tasks serão geradas lá
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Criar um arquivo de log para armazenar os resultados do cron
RUN touch /var/log/cron.log

# Executar o entrypoint
ENTRYPOINT ["/entrypoint.sh"]
