version: '3'
services:
  cluster-node:
    container_name: cluster-node
    restart: unless-stopped
    image: eduardosilva/wireguard-webadmin-cluster-node:latest
    environment:
      - MASTER_SERVER_ADDRESS=${MASTER_SERVER_ADDRESS}
      - DEBUG_MODE=${DEBUG_MODE}
      - COMPOSE_VERSION=c1b
      - TZ=${TIMEZONE}
      - TOKEN=${TOKEN}
    volumes:
      - cluster_node_wireguard:/etc/wireguard
      - cluster_node_dnsmasq_conf:/etc/dnsmasq/
    ports:
      # Ports for WireGuard instances.
      - "51820-51839:51820-51839/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1

  cluster-node-dns:
    container_name: cluster-node-dns
    restart: unless-stopped
    image: eduardosilva/wireguard_webadmin_dns:latest
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - cluster_node_dnsmasq_conf:/etc/dnsmasq/
volumes:
  cluster_node_wireguard:
  cluster_node_dnsmasq_conf:
