version: '3'
services:
  wireguard-webadmin-cluster-node:
    container_name: wireguard-webadmin-cluster-node
    restart: unless-stopped
    build:
      context: containers/cluster_node
      dockerfile: Dockerfile-cluster_node
    environment:
      - MASTER_SERVER_ADDRESS=${MASTER_SERVER_ADDRESS}
      - DEBUG_MODE=${DEBUG_MODE}
      - COMPOSE_VERSION=03r
      - TZ=${TIMEZONE}
      - TOKEN=${TOKEN}
    volumes:
      - cluster_node_wireguard:/etc/wireguard
    #ports:
      # Ports for WireGuard instances.
      #- "51820-51839:51820-51839/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1

volumes:
  cluster_node_wireguard:
