# Generated by Django 5.2.9 on 2026-01-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WireguardStatusCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_type', models.CharField(choices=[('master', 'Master'), ('cluster', 'Cluster')], max_length=16)),
                ('data', models.JSONField()),
                ('processing_time_ms', models.PositiveIntegerField()),
                ('uuid', models.UUIDField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
