# Generated by Django 5.2.12 on 2026-03-12 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeper', '0002_alter_authmethod_auth_type_gatekeeperipaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authmethodalloweddomain',
            name='auth_method',
            field=models.ForeignKey(limit_choices_to={'auth_type': 'oidc'}, on_delete=django.db.models.deletion.CASCADE, related_name='allowed_domains', to='gatekeeper.authmethod'),
        ),
        migrations.AlterField(
            model_name='authmethodallowedemail',
            name='auth_method',
            field=models.ForeignKey(limit_choices_to={'auth_type': 'oidc'}, on_delete=django.db.models.deletion.CASCADE, related_name='allowed_emails', to='gatekeeper.authmethod'),
        ),
    ]
