# Generated by Django 5.2.12 on 2026-03-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeper', '0003_alter_authmethodalloweddomain_auth_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatekeeperipaddress',
            name='prefix_length',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
