# Generated by Django 5.2.12 on 2026-03-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeper', '0004_alter_gatekeeperipaddress_prefix_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='authmethod',
            name='totp_before_auth',
            field=models.BooleanField(default=False),
        ),
    ]
