# Generated by Django 5.2.12 on 2026-03-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeper', '0005_authmethod_totp_before_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatekeeperuser',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
