# Generated by Django 5.2.12 on 2026-03-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeper', '0006_gatekeeperuser_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authmethod',
            name='totp_before_auth',
        ),
        migrations.RemoveField(
            model_name='gatekeeperuser',
            name='password_hash',
        ),
        migrations.AlterField(
            model_name='gatekeeperuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='gatekeeperuser',
            name='password',
            field=models.CharField(blank=True, help_text='Password for local authentication (leave blank if not using)', max_length=250),
        ),
    ]
