# Generated by Django 5.2.12 on 2026-03-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeper', '0008_authmethod_session_expiration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authmethod',
            name='session_expiration_minutes',
            field=models.PositiveIntegerField(default=720, help_text='Session expiration time in minutes'),
        ),
    ]
