# Generated by Django 5.2.12 on 2026-03-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeper', '0009_alter_authmethod_session_expiration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatekeeperuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
