# Generated by Django 5.2.9 on 2026-01-15 21:22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wireguard', '0027_alter_wireguardinstance_peer_list_refresh_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_template', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
                ('route_type', models.CharField(choices=[('default', 'Default Route (0.0.0.0/0)'), ('peer_same_instance', 'Routes from Peers on same Interface'), ('peer_all_instances', 'Routes from All Peers'), ('custom', 'Custom Routes')], max_length=20)),
                ('custom_routes', models.TextField(blank=True, help_text='One route per line in CIDR notation.', null=True)),
                ('allow_peer_custom_routes', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('wireguard_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wireguard.wireguardinstance')),
            ],
            options={
                'unique_together': {('wireguard_instance', 'name')},
            },
        ),
    ]
