# Generated by Django 5.2.9 on 2026-01-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingtemplate',
            name='enforce_route_policy',
            field=models.BooleanField(default=False),
        ),
    ]
