# Generated by Django 5.1.5 on 2025-02-25 12:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='email_settings', max_length=20, unique=True)),
                ('smtp_username', models.CharField(blank=True, max_length=100, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=100, null=True)),
                ('smtp_host', models.CharField(blank=True, max_length=100, null=True)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_encryption', models.CharField(choices=[('ssl', 'SSL'), ('tls', 'TLS')], default='tls', max_length=3)),
                ('smtp_from_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
