# Generated by Django 5.1.5 on 2025-02-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
