# Generated by Django 5.1.5 on 2025-03-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard_tools', '0002_emailsettings_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_encryption',
            field=models.CharField(choices=[('ssl', 'SSL'), ('tls', 'TLS'), ('none', 'None (Insecure)'), ('noauth', 'No authentication (Insecure)')], default='tls', max_length=6),
        ),
    ]
