FROM caddy:2-alpine

COPY entrypoint.sh /usr/local/bin/caddy-entrypoint.sh

RUN chmod +x /usr/local/bin/caddy-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/caddy-entrypoint.sh"]
CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
