# Generated by Django 5.1.5 on 2025-02-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_invite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitesettings',
            name='required_user_level',
            field=models.PositiveIntegerField(choices=[(20, 'View Only User'), (30, 'Peer Manager'), (40, 'Wireguard Manager'), (50, 'Administrator')], default=30),
        ),
    ]
