# Generated by Django 5.1.5 on 2025-02-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_invite', '0002_invitesettings_required_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitesettings',
            name='invite_text_body',
            field=models.TextField(default='Here is your WireGuard VPN invite link: {invite_url}. The link expires in {expire_minutes} minutes.'),
        ),
        migrations.AlterField(
            model_name='invitesettings',
            name='invite_email_body',
            field=models.TextField(default='Here is your WireGuard VPN invite link: {invite_url}. The link expires in {expire_minutes} minutes.'),
        ),
        migrations.AlterField(
            model_name='invitesettings',
            name='invite_whatsapp_body',
            field=models.TextField(default='Here is your WireGuard VPN invite link: {invite_url}. The link expires in {expire_minutes} minutes.'),
        ),
    ]
