# Generated by Django 5.1.5 on 2025-02-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_invite', '0003_invitesettings_invite_text_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitesettings',
            name='required_user_level',
            field=models.PositiveIntegerField(choices=[(20, 'View Only User'), (30, 'Peer Manager'), (40, 'Wireguard Manager'), (50, 'Administrator')], default=50),
        ),
    ]
