# Generated by Django 5.1.5 on 2025-03-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_invite', '0006_alter_invitesettings_invite_email_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitesettings',
            name='download_5_label',
            field=models.CharField(blank=True, default='Linux', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='invitesettings',
            name='invite_email_body',
            field=models.TextField(default="\nHello,\n\nYou're invited to join our secure WireGuard VPN network. Please click the link below to access your personalized VPN configuration:\n\n{invite_url}\n\nNote: This invitation link will expire in {expire_minutes} minutes. If you need a new link after expiration, please request another invite.\n"),
        ),
        migrations.AlterField(
            model_name='invitesettings',
            name='invite_text_body',
            field=models.TextField(default="\nHello,\n\nYou're invited to join our secure WireGuard VPN network. Please click the link below to access your personalized VPN configuration:\n\n{invite_url}\n\nNote: This invitation link will expire in {expire_minutes} minutes. If you need a new link after expiration, please request another invite.\n"),
        ),
        migrations.AlterField(
            model_name='invitesettings',
            name='invite_whatsapp_body',
            field=models.TextField(default="\nHello,\n\nYou're invited to join our secure WireGuard VPN network. Please click the link below to access your personalized VPN configuration:\n\n{invite_url}\n\nNote: This invitation link will expire in {expire_minutes} minutes. If you need a new link after expiration, please request another invite.\n"),
        ),
    ]
