# Generated by Django 5.2 on 2025-04-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_invite', '0007_alter_invitesettings_download_5_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitesettings',
            name='invite_email_body',
            field=models.TextField(default="Hello,\n\nYou're invited to join our secure WireGuard VPN network. Please click the link below to access your personalized VPN configuration:\n\n{invite_url}\n\nNote: This invitation link will expire in {expire_minutes} minutes. If you need a new link after expiration, please request another invite."),
        ),
        migrations.AlterField(
            model_name='invitesettings',
            name='invite_text_body',
            field=models.TextField(default="Hello,\n\nYou're invited to join our secure WireGuard VPN network. Please click the link below to access your personalized VPN configuration:\n\n{invite_url}\n\nNote: This invitation link will expire in {expire_minutes} minutes. If you need a new link after expiration, please request another invite."),
        ),
        migrations.AlterField(
            model_name='invitesettings',
            name='invite_whatsapp_body',
            field=models.TextField(default="Hello,\n\nYou're invited to join our secure WireGuard VPN network. Please click the link below to access your personalized VPN configuration:\n\n{invite_url}\n\nNote: This invitation link will expire in {expire_minutes} minutes. If you need a new link after expiration, please request another invite."),
        ),
        migrations.AlterField(
            model_name='invitesettings',
            name='required_user_level',
            field=models.PositiveIntegerField(choices=[(20, 'View Only'), (30, 'Peer Manager'), (40, 'WireGuard Manager'), (50, 'Administrator')], default=50),
        ),
    ]
