# Generated by Django 5.1.5 on 2025-01-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0003_authenticationtoken'),
        ('wireguard', '0023_peergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracl',
            name='peer_groups',
            field=models.ManyToManyField(blank=True, to='wireguard.peergroup'),
        ),
    ]
