# Generated by Django 5.1.5 on 2025-01-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0004_useracl_peer_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracl',
            name='enable_console',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useracl',
            name='enable_enhanced_filter',
            field=models.BooleanField(default=False),
        ),
    ]
