# Generated by Django 5.2 on 2025-04-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0005_useracl_enable_console_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracl',
            name='enable_reload',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useracl',
            name='enable_restart',
            field=models.BooleanField(default=True),
        ),
    ]
