# Generated by Django 5.2 on 2025-04-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0006_useracl_enable_reload_useracl_enable_restart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracl',
            name='user_level',
            field=models.PositiveIntegerField(choices=[(10, 'Debugging Analyst'), (20, 'View Only'), (30, 'Peer Manager'), (40, 'WireGuard Manager'), (50, 'Administrator')], default=0),
        ),
    ]
