# Generated by Django 5.0.2 on 2024-02-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectrule',
            name='masquerade_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='redirectrule',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
    ]
