# Generated by Django 5.0.2 on 2024-02-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0004_rename_forwardrule_firewallrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallsettings',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='firewallsettings',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
