# Generated by Django 5.0.2 on 2024-02-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0005_firewallsettings_created_firewallsettings_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallsettings',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
