# Generated by Django 5.0.2 on 2024-02-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0006_alter_firewallsettings_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallsettings',
            name='pending_changes',
            field=models.BooleanField(default=False),
        ),
    ]
