# Generated by Django 5.0.2 on 2024-02-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0007_firewallsettings_pending_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewallsettings',
            name='global',
        ),
        migrations.AddField(
            model_name='firewallsettings',
            name='name',
            field=models.CharField(default='global', max_length=6, unique=True),
        ),
    ]
