# Generated by Django 5.0.2 on 2024-03-01 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0008_remove_firewallsettings_global_firewallsettings_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewallrule',
            name='wireguard_instance',
        ),
    ]
