# Generated by Django 5.0.2 on 2024-03-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0009_remove_firewallrule_wireguard_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallrule',
            name='firewall_chain',
            field=models.CharField(choices=[('forward', 'FORWARD'), ('postrouting', 'POSTROUTING (nat)')], default='forward', max_length=12),
        ),
    ]
