# Generated by Django 5.1.5 on 2025-03-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0011_firewallsettings_last_firewall_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectrule',
            name='port_forward_to',
            field=models.PositiveIntegerField(default=8080),
        ),
    ]
