# Generated by Django 5.1.5 on 2025-03-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0012_redirectrule_port_forward_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redirectrule',
            name='port_forward_to',
        ),
    ]
