# Generated by Django 5.1.5 on 2025-03-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0013_remove_redirectrule_port_forward_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectrule',
            name='port_forward',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
