# Generated by Django 5.2.9 on 2025-12-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0014_redirectrule_port_forward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallsettings',
            name='default_forward_policy',
            field=models.CharField(choices=[('accept', 'ACCEPT'), ('drop', 'DROP')], default='accept', max_length=6),
        ),
        migrations.AlterField(
            model_name='firewallsettings',
            name='default_output_policy',
            field=models.CharField(choices=[('accept', 'ACCEPT'), ('drop', 'DROP')], default='accept', max_length=6),
        ),
    ]
