# Generated by Django 5.2.9 on 2026-02-03 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0015_alter_firewallsettings_default_forward_policy_and_more'),
        ('wireguard', '0032_remove_peer_enabled_by_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallsettings',
            name='instance_to_execute_firewall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wireguard.wireguardinstance'),
        ),
    ]
