# Generated by Django 5.2.11 on 2026-02-09 23:31

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wireguard', '0032_remove_peer_enabled_by_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('allow_restart', models.BooleanField(default=True)),
                ('allow_reload', models.BooleanField(default=True)),
                ('allow_export', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('allowed_instances', models.ManyToManyField(blank=True, related_name='api_keys', to='wireguard.wireguardinstance')),
            ],
        ),
    ]
