# Generated by Django 5.2.11 on 2026-02-10 00:54

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0001_initial'),
        ('wireguard', '0032_remove_peer_enabled_by_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='allow_export',
            field=models.BooleanField(default=True, verbose_name='Allow Export'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='allow_reload',
            field=models.BooleanField(default=True, verbose_name='Allow Reload'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='allow_restart',
            field=models.BooleanField(default=True, verbose_name='Allow Restart'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='allowed_instances',
            field=models.ManyToManyField(blank=True, related_name='api_keys', to='wireguard.wireguardinstance', verbose_name='Allowed Instances'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token'),
        ),
    ]
