# Generated by Django 5.0.1 on 2024-02-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='private_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
