# Generated by Django 5.0.1 on 2024-02-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0002_peer_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerallowedip',
            name='missing_from_wireguard',
            field=models.BooleanField(default=False),
        ),
    ]
