# Generated by Django 5.0.1 on 2024-02-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0003_peerallowedip_missing_from_wireguard'),
    ]

    operations = [
        migrations.AddField(
            model_name='wireguardinstance',
            name='public_key',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
