# Generated by Django 5.0.1 on 2024-02-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0004_wireguardinstance_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='wireguardinstance',
            name='pending_changes',
            field=models.BooleanField(default=True),
        ),
    ]
