# Generated by Django 5.0.1 on 2024-02-16 19:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0005_wireguardinstance_pending_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerStatus',
            fields=[
                ('last_handshake', models.DateTimeField(blank=True, null=True)),
                ('transfer_rx', models.BigIntegerField(default=0)),
                ('transfer_tx', models.BigIntegerField(default=0)),
                ('latest_config', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('peer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wireguard.peer')),
            ],
        ),
    ]
