# Generated by Django 5.0.1 on 2024-02-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0006_peerstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wireguardinstance',
            name='persistent_keepalive',
        ),
    ]
