# Generated by Django 5.0.1 on 2024-02-22 17:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0008_wireguardinstance_dns_primary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebadminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webadmin_settings', models.CharField(max_length=20, unique=True)),
                ('update_available', models.BooleanField(default=False)),
                ('current_version', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('latest_version', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
