# Generated by Django 5.0.1 on 2024-02-22 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0009_webadminsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webadminsettings',
            name='webadmin_settings',
        ),
    ]
