# Generated by Django 5.0.1 on 2024-02-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0011_webadminsettings_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webadminsettings',
            name='current_version',
        ),
        migrations.RemoveField(
            model_name='webadminsettings',
            name='latest_version',
        ),
    ]
