# Generated by Django 5.0.1 on 2024-02-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0012_remove_webadminsettings_current_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webadminsettings',
            name='current_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webadminsettings',
            name='latest_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
