# Generated by Django 5.0.2 on 2024-02-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0015_alter_wireguardinstance_dns_primary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wireguardinstance',
            name='dns_primary',
        ),
        migrations.RemoveField(
            model_name='wireguardinstance',
            name='dns_secondary',
        ),
    ]
