# Generated by Django 5.0.2 on 2024-02-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0016_remove_wireguardinstance_dns_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wireguardinstance',
            name='dns_primary',
            field=models.GenericIPAddressField(default='1.1.1.1', protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='wireguardinstance',
            name='dns_secondary',
            field=models.GenericIPAddressField(blank=True, default='1.0.0.1', null=True, protocol='IPv4'),
        ),
    ]
