# Generated by Django 5.0.2 on 2024-02-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0017_wireguardinstance_dns_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wireguardinstance',
            name='legacy_firewall',
            field=models.BooleanField(default=True),
        ),
    ]
