# Generated by Django 5.0.2 on 2024-03-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0018_wireguardinstance_legacy_firewall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wireguardinstance',
            name='legacy_firewall',
            field=models.BooleanField(default=False),
        ),
    ]
