# Generated by Django 5.0.2 on 2024-03-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0020_peerallowedip_config_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peerallowedip',
            name='missing_from_wireguard',
        ),
    ]
