# Generated by Django 5.1.5 on 2025-01-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0022_alter_wireguardinstance_dns_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerGroup',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('peer', models.ManyToManyField(blank=True, to='wireguard.peer')),
                ('server_instance', models.ManyToManyField(blank=True, to='wireguard.wireguardinstance')),
            ],
        ),
    ]
