# Generated by Django 5.1.5 on 2025-01-20 13:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0023_peergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peergroup',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
