# Generated by Django 5.1.5 on 2025-01-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0024_alter_peergroup_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
