# Generated by Django 5.1.5 on 2025-02-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0025_peer_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='webadminsettings',
            name='db_patch_version',
            field=models.IntegerField(default=0),
        ),
    ]
