# Generated by Django 5.1.5 on 2025-02-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0026_webadminsettings_db_patch_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wireguardinstance',
            name='peer_list_refresh_interval',
            field=models.IntegerField(default=10),
        ),
    ]
