# Generated by Django 5.2.9 on 2026-01-22 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing_templates', '0002_routingtemplate_enforce_route_policy'),
        ('wireguard', '0027_alter_wireguardinstance_peer_list_refresh_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='routing_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peers', to='routing_templates.routingtemplate'),
        ),
    ]
