# Generated by Django 5.2.9 on 2026-01-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0028_peer_routing_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='wireguardinstance',
            name='enforce_route_policy',
            field=models.BooleanField(default=False),
        ),
    ]
