# Generated by Django 5.2.9 on 2026-01-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0029_wireguardinstance_enforce_route_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='enabled_by_schedule',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='peer',
            name='suspend_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peer',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
