# Generated by Django 5.2.9 on 2026-02-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0030_peer_enabled_by_schedule_peer_suspend_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='disabled_by_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
