# Generated by Django 5.2.9 on 2026-02-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0031_peer_disabled_by_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peer',
            name='enabled_by_schedule',
        ),
    ]
