# Generated by Django 5.2.5 on 2025-08-15 00:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='cluster_settings', max_length=16, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('primary_enable_wireguard', models.BooleanField(default=True)),
                ('stats_sync_interval', models.IntegerField(default=60)),
                ('stats_cache_interval', models.IntegerField(default=60)),
                ('cluster_mode', models.CharField(default='mirror', max_length=16)),
                ('restart_mode', models.CharField(choices=[('auto', 'Automatically restart/reload'), ('manual', 'Manual')], default='auto', max_length=16)),
                ('worker_display', models.CharField(choices=[('name', 'Name'), ('server_address', 'Server Address'), ('location', 'Location'), ('address_location', 'Address + Location')], default='server_address', max_length=16)),
                ('config_version', models.PositiveIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('ip_lock', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('force_reload', models.BooleanField(default=False)),
                ('force_restart', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_reload', models.DateTimeField(blank=True, null=True)),
                ('last_restart', models.DateTimeField(blank=True, null=True)),
                ('config_version', models.PositiveIntegerField(default=0)),
                ('config_pending', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cluster.worker')),
            ],
        ),
    ]
