# Generated by Django 5.2.5 on 2025-08-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerstatus',
            name='active_peers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
