# Generated by Django 5.2.5 on 2025-08-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_workerstatus_active_peers'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerstatus',
            name='wireguard_status',
            field=models.JSONField(default=dict),
        ),
    ]
