# Generated by Django 5.2.9 on 2025-12-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0003_workerstatus_wireguard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustersettings',
            name='cluster_mode',
            field=models.CharField(choices=[('mirror', 'Mirror')], default='mirror', max_length=16),
        ),
    ]
