# Generated by Django 5.2.9 on 2025-12-29 20:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0004_alter_clustersettings_cluster_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
