# Generated by Django 5.2.9 on 2025-12-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0005_alter_worker_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='error_status',
            field=models.CharField(choices=[('', ''), ('ip_lock', 'IP lock is enabled, but the worker is attempting to access from a different IP address.'), ('worker_disabled', 'Worker is not enabled'), ('cluster_disabled', 'Cluster is not enabled')], default='', max_length=32),
        ),
    ]
