# Generated by Django 5.2.9 on 2025-12-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0006_worker_error_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerstatus',
            name='worker_version',
            field=models.BooleanField(default=0),
        ),
    ]
