# Generated by Django 5.2.9 on 2025-12-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0009_alter_worker_error_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='error_status',
            field=models.CharField(choices=[('', ''), ('ip_lock', 'IP lock is enabled, but the worker is attempting to access from a different IP address.'), ('worker_disabled', 'Worker is not enabled'), ('cluster_disabled', 'Cluster is not enabled'), ('missing_version', 'Please report worker_config_version and worker_version in the API request.'), ('update_required', 'Worker update is required.')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='workerstatus',
            name='worker_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
