# Generated by Django 5.2.9 on 2025-12-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0010_alter_worker_error_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustersettings',
            name='dns_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerstatus',
            name='dns_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
