# Generated by Django 5.2.9 on 2025-12-31 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0011_clustersettings_dns_version_workerstatus_dns_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerstatus',
            name='config_pending',
        ),
    ]
