# Generated by Django 5.2.9 on 2026-01-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0012_remove_workerstatus_config_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustersettings',
            name='restart_mode',
            field=models.CharField(choices=[('auto', 'Automatic restart')], default='auto', max_length=16),
        ),
        migrations.AlterField(
            model_name='worker',
            name='error_status',
            field=models.CharField(choices=[('', ''), ('ip_lock', 'IP lock is enabled, but the worker is attempting to access from a different IP address.'), ('worker_disabled', 'Worker is not enabled'), ('cluster_disabled', 'Cluster is not enabled'), ('missing_version', 'Please report worker_config_version, worker_dns_version and worker_version in the API request.'), ('update_required', 'Worker update is required.')], default='', max_length=32),
        ),
    ]
