# Generated by Django 5.2.9 on 2026-01-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0013_alter_clustersettings_restart_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clustersettings',
            name='stats_cache_interval',
        ),
        migrations.RemoveField(
            model_name='clustersettings',
            name='stats_sync_interval',
        ),
    ]
