# Generated by Django 5.2.9 on 2026-01-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0014_remove_clustersettings_stats_cache_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerstatus',
            name='wireguard_status',
            field=models.JSONField(),
        ),
    ]
