# Generated by Django 5.2.9 on 2026-01-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0015_alter_workerstatus_wireguard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerstatus',
            name='wireguard_status_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
