# Generated by Django 5.2.9 on 2026-01-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0016_workerstatus_wireguard_status_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerstatus',
            name='wireguard_status',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
