# Generated by Django 5.2.12 on 2026-03-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='display_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
