# Generated by Django 5.2.12 on 2026-03-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gateway', '0004_alter_application_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationroute',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
