# Generated by Django 5.2.12 on 2026-03-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gateway', '0005_alter_applicationroute_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspolicy',
            name='policy_type',
            field=models.CharField(choices=[('public', 'Public'), ('protected', 'Protected'), ('deny', 'Deny')], max_length=32),
        ),
    ]
