# Generated by Django 5.1.5 on 2025-03-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0002_dnsfilterlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsfilterlist',
            name='host_count',
            field=models.IntegerField(default=0),
        ),
    ]
