# Generated by Django 5.1.5 on 2025-03-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0003_dnsfilterlist_host_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsfilterlist',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
