# Generated by Django 5.2.9 on 2026-01-28 14:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wireguard', '0030_peer_enabled_by_schedule_peer_suspend_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='PeerScheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_scheduled_enable_at', models.DateTimeField(blank=True, null=True)),
                ('next_scheduled_disable_at', models.DateTimeField(blank=True, null=True)),
                ('schedule_last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('next_manual_suspend_at', models.DateTimeField(blank=True, null=True)),
                ('next_manual_unsuspend_at', models.DateTimeField(blank=True, null=True)),
                ('manual_suspend_reason', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('peer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='wireguard.peer')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.scheduleprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['next_scheduled_enable_at'], name='scheduler_p_next_sc_ef2e87_idx'), models.Index(fields=['next_scheduled_disable_at'], name='scheduler_p_next_sc_203dba_idx'), models.Index(fields=['next_manual_suspend_at'], name='scheduler_p_next_ma_31b89c_idx'), models.Index(fields=['next_manual_unsuspend_at'], name='scheduler_p_next_ma_b980b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('end_weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='scheduler.scheduleprofile')),
            ],
            options={
                'ordering': ('start_weekday', 'start_time'),
                'constraints': [models.UniqueConstraint(fields=('profile', 'start_weekday', 'end_weekday', 'start_time', 'end_time'), name='uniq_slot_per_profile')],
            },
        ),
    ]
