# Generated by Django 5.2.11 on 2026-02-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_scheduleslot_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peerscheduling',
            name='schedule_last_calculated_at',
        ),
    ]
