# Generated by Django 5.2.11 on 2026-02-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_remove_peerscheduling_schedule_last_calculated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleprofile',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
